[package]
name = "voxel"
version = "0.1.0"
edition = "2024"

[dependencies]
# anyhow = "1.0.100"
# bytemuck = { version = "1.24.0", features = ["derive"] }
# csscolorparser = "0.8.1"
# env_logger = "0.11.8"
# glam = "0.30.10"
# image = "0.25.9"
# indexmap = "2.13.0"
# log = "0.4.29"
# noise = "0.9.0"
# num-derive = "0.4.2"
# num-traits = "0.2.19"
# oneshot = "0.1.12"
# pollster = "0.4.0"
# rayon = "1.11.0"
# strum = { version = "0.27.2", features = ["derive"] }
# wgpu = "28.0.0"
# winit = "0.30.12"
# egui = { git = "https://github.com/SuchAFuriousDeath/egui", rev = "cf4060c5bf142952c1a8c49a3f6aa4b5cbb0d6fc" }
# egui-winit = { git = "https://github.com/SuchAFuriousDeath/egui", rev = "cf4060c5bf142952c1a8c49a3f6aa4b5cbb0d6fc" }
# egui-wgpu = { git = "https://github.com/SuchAFuriousDeath/egui", rev = "cf4060c5bf142952c1a8c49a3f6aa4b5cbb0d6fc", features = ["winit"] }
bevy = { version = "0.18.0", features = ["bevy_dev_tools"] }
bevy_egui = "0.39.0"
csscolorparser = "0.8.1"
image = "0.25.9"
indexmap = "2.13.0"
log = "0.4.29"
noise = "0.9.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
strum = { version = "0.27.2", features = ["derive"] }
